### ISSUE TITLE
Selection of the alpha value

### ISSUE THREAD

**Issue by chenzhi1992** [natanielruiz/deep-head-pose#54]
When I trained the hopenet model， the alpha value is 0.001 in ‘train_hopenet.py’ . However, the alpha value is 1 or 2 in your paper. When I changed the alpha value from 1 to 2, the lose is very large(Losses: Yaw 2683.0190, Pitch 78.4215, Roll 88.7859). How should I select the alpha value?
Thanks!

**Comment by natanielruiz** [comment]
Hi,
I used 1 or 2 for the alpha value for the models that I am distributing. I was using an older version of PyTorch so maybe that can have something to do with it, but I am not sure why you're getting very high losses. I'm sorry I cannot devote too much time into this right now as I have other stuff that I am working on. If you have any luck then please update this thread, will leave it open since someone might have an answer.

**Comment by chenzhi1992** [comment]
The version of my PyTorch is 1.0 . I will try an older version.
Thanks.

**Comment by shiyuanyin** [comment]
@chenzhi1992 ,hello ，I have the same problem，Excuse me?Has the problem been solved?，if alpha =1or 2
Ready to train network.
Epoch [1/25], Iter [100/3825] Losses: Yaw 676.8770, Pitch 435.5157, Roll 283.9487
676.87701416
Epoch [1/25], Iter [200/3825] Losses: Yaw 414.7014, Pitch 332.6989, Roll 331.9659
414.701385498
Epoch [1/25], Iter [300/3825] Losses: Yaw 250.8026, Pitch 189.7498, Roll 132.9687
